name: Deploy Frontend to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure frontend folder exists on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/frontend

      - name: Copy frontend files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./*"
          target: "/home/${{ secrets.EC2_USER }}/frontend"
          strip_components: 0
          rm: true

      - name: Install dependencies & build frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/frontend

            echo "Checking Node.js..."
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            echo "Installing frontend dependencies..."
            npm install

            echo "Building frontend..."
            npm run build

            echo "Checking Serve..."
            if ! command -v serve &> /dev/null; then
              sudo npm install -g serve
            fi

            echo "Restarting frontend..."
            pm2 delete frontend || true
            pm2 start "serve -s build -l 3001" --name frontend
            pm2 save
